FROM ruby:3.4.10-slim-bookworm

RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
      build-essential \
      git \
      libpq-dev \
      libyaml-dev \
      pkg-config && \
    rm -rf /var/lib/apt/lists/*

RUN gem install rails -v 7.2.3.1 --no-document

WORKDIR /app